// Ritika's Memory Arcade — edit this one file to adjust copy, answers, and tickets.
// Quiz answer indices are zero-based: 0 is the first choice, 1 the second, and so on.
export const publicAsset = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

export const memoryData = {
  site: {
    herName: "Ritika",
    herNickname: "Ritika",
    yourName: "Gopinath Varadarajan",
    eyebrow: "A magical birthday adventure, made just for you",
    title: "Ritika's Memory Arcade",
    greeting: "Happy Birthday, Ritika!",
    intro:
      "Seven memories, five questions, and a little birthday magic are waiting inside. Ready to revisit some of our best adventures?",
    enterLabel: "Start your birthday adventure ✦",
    music: {
      title: "Hedwig's Theme",
      credit: "John Williams · official YouTube audio",
      youtubeId: "wtHra9tFISY",
      sourceUrl: "https://www.youtube.com/watch?v=wtHra9tFISY",
    },
    theme: {
      paper: "#fffaf0",
      cocoa: "#4d3636",
      rose: "#d97d91",
      blush: "#f5c6ce",
      peach: "#f6c7a5",
      lavender: "#c8b8dc",
      sage: "#b7c8ae",
      butter: "#f5df91",
      night: "#211a35",
      gold: "#c49b4a",
    },
  },

  milestones: [
    {
      id: "scotland",
      number: "01",
      title: "New Year in Scotland",
      date: "THE GROUP ADVENTURE",
      icon: "✈",
      position: { x: 21, y: 7 },
      photo: publicAsset("/photos/02-scotland.webp?v=1"),
      photoPortrait: true,
      caption: "One nervous flight and an unforgettable New Year.",
      story:
        "Scotland began with you being absolutely terrified of getting on the flight—and somehow that made the adventure even more unforgettable. Once we arrived, the nerves gave way to an amazing New Year with our friends. There was something special about all of us being together, away from the usual routine, welcoming a new year as one happy group. It became one of those trips we can still picture clearly: the excitement, the laughter, and the relief that the scary flight had carried us somewhere completely worth visiting.",
    },
    {
      id: "birmingham",
      number: "02",
      title: "Our Birmingham Beginning",
      date: "OUR FIRST TRIP TOGETHER",
      icon: "🐧",
      position: { x: 75, y: 20 },
      photo: publicAsset("/photos/01-birmingham.webp?v=1"),
      photoPortrait: true,
      caption: "Penguins, a lovely lunch, and our very first trip together.",
      story:
        "Birmingham will always be special because it was our first-ever trip together. We spent the day exploring the aquatic world, and seeing how happy you were around the penguins made the whole place feel even more memorable. After wandering through all the exhibits, we found a good lunch, talked about everything and nothing, and eventually made our way home. It was a simple day, but it became the first page in a much bigger collection of adventures. Every trip that followed began with us choosing to take this one together.",
    },
    {
      id: "nottingham",
      number: "03",
      title: "A Nottingham Kind of Day",
      date: "IKEA TO ROBIN HOOD",
      icon: "🏹",
      position: { x: 27, y: 33 },
      photo: publicAsset("/photos/04-nottingham.webp?v=1"),
      photoPortrait: true,
      caption: "IKEA wandering, Robin Hood, and a well-earned beer.",
      story:
        "Nottingham was one entire, wonderfully random day trip. We explored IKEA as though every room display was part of the attraction, looking at all the things we did and did not need. By evening we had moved on to the Robin Hood area, where we slowed down, sat together, and had a beer. Nothing needed to be rushed or overly planned. From furniture showrooms to a legendary outlaw, the whole day somehow made sense because we were exploring it together.",
    },
    {
      id: "london-zoo",
      number: "04",
      title: "A Wild Day at the Zoo",
      date: "LONDON ZOO",
      icon: "🦒",
      position: { x: 76, y: 46 },
      photo: publicAsset("/photos/06-london-zoo.webp?v=1"),
      photoPortrait: true,
      caption: "A full day with the animals you could not wait to meet.",
      story:
        "You had always wanted a proper day surrounded by animals, so London Zoo had your name written all over it. We spent the day moving from one enclosure to the next, discovering favourites and stopping whenever something caught your attention. Watching you enjoy the animals was as much fun as the zoo itself. It was a bright, easy day that felt like a small holiday within London—and another reminder that your excitement can make even a familiar city feel completely new.",
    },
    {
      id: "brighton",
      number: "05",
      title: "Brave in Brighton",
      date: "THE BEACH & THE RIDE",
      icon: "🎡",
      position: { x: 24, y: 59 },
      photo: publicAsset("/photos/03-brighton.webp?v=1"),
      photoPortrait: true,
      caption: "A dream beach day—and one ride you will never forget.",
      story:
        "Brighton gave us the perfect combination of something you had always wanted and something you definitely did not want. We finally made it to the beach, a place you had been excited to visit, and enjoyed the sea air and the freedom of being away for the day. Then came the ride. You were so frightened that you started crying after sitting down, and although it was dramatic at the time, it has become one of our funniest memories. You were scared, brave, and completely unforgettable all at once. Brighton still makes me smile for exactly that reason.",
    },
    {
      id: "canary-wharf",
      number: "06",
      title: "The Heatwave Escape",
      date: "CANARY WHARF, LONDON",
      icon: "☀",
      position: { x: 74, y: 73 },
      photo: publicAsset("/photos/05-canary-wharf.webp?v=1"),
      photoPortrait: true,
      caption: "Too hot at home, so London became our evening plan.",
      story:
        "During that London heatwave, home was simply too hot for you to sit in. So you came all the way to my office at J.P. Morgan in Canary Wharf, and an uncomfortable day turned into a really good evening. We wandered around Canary Wharf, explored the area, and escaped the heat as best we could before ending with a great dinner. I still remember it because there was no grand plan—just you showing up, the two of us making the most of the day, and London giving us another memory in return.",
    },
    {
      id: "london-food",
      number: "07",
      title: "Our London Food Trail",
      date: "RESTAURANTS & CAFÉS",
      icon: "☕",
      position: { x: 31, y: 88 },
      photo: publicAsset("/photos/07-london-food.webp?v=1"),
      photoPortrait: true,
      caption: "So many meals, cafés, conversations, and reasons to order dessert.",
      story:
        "Since moving to London, we have built a map within the map: all the restaurants and cafés we have tried together. Some became favourites, some were one-time experiments, and a few were chosen simply because we were hungry and nearby. Every table gave us time to talk, laugh, plan the next outing, and debate what to order. From comforting meals to spontaneous café stops, this ongoing food trail is not one memory but dozens—and it is still growing every time we discover somewhere new.",
    },
  ],

  quizQuestions: [
    {
      prompt: "Which animal is Ritika most frightened of?",
      choices: ["Snakes", "Dogs", "Spiders"],
      correctAnswer: 1,
      hint: "Even the friendliest wagging tail can cause an immediate change of route.",
      success: "Correct. The dogs may be friendly, but Ritika is maintaining a safe distance.",
    },
    {
      prompt: "Which of our trips did Ritika enjoy the most?",
      choices: ["Scotland", "Birmingham", "Brighton"],
      correctAnswer: 2,
      hint: "Think beach, sea air, and one slightly terrifying ride.",
      success: "Brighton! Tears on the ride, happiness everywhere else.",
    },
    {
      prompt: "Which food could Ritika happily eat again and again?",
      choices: ["Pasta", "Rice", "Pizza"],
      correctAnswer: 1,
      hint: "It belongs at the centre of a very satisfying South Indian meal.",
      success: "Rice wins—as everyone who has ever shared a meal with Ritika already knows.",
    },
    {
      prompt: "Which phrase best describes Ritika's ideal life plan?",
      choices: [
        "வேலை செய்யணும், ஓடணும், பிஸியாக இருக்கணும்",
        "சாப்பிடணும், தூங்கணும், ஜாலியாக இருக்கணும்",
        "ஜிம் போகணும், டயட் பண்ணணும், சீக்கிரம் எழுந்திருக்கணும்",
      ],
      correctAnswer: 1,
      hint: "Eat well, sleep well, and enjoy life. That is the entire strategy.",
      success: "சாப்பிடணும், தூங்கணும், ஜாலியாக இருக்கணும் — the perfect philosophy.",
    },
    {
      prompt: "Which magical world does Ritika love more than anything?",
      choices: ["The Lord of the Rings", "Harry Potter", "Star Wars"],
      correctAnswer: 1,
      hint: "Somewhere, a wand is waiting to choose its witch.",
      success: "Harry Potter, obviously. Ten points to Ritika!",
    },
  ],

  hiddenMessage: {
    eyebrow: "Birthday level unlocked",
    heading: "Happy 26th Birthday, Ritika!",
    paragraphs: [
      "You have faced plenty of challenges, but every one of them has shown how strong you can be. Whatever comes next, you are only going to become braver, wiser, and even more capable.",
      "I hope this year brings you good health, exciting opportunities, peaceful days, plenty of laughter, amazing food, and all the happiness you deserve.",
      "And now for the important announcement: you are officially a 26-year-old auntie. Please use this new level of wisdom responsibly—preferably while eating rice, taking a nap, and enjoying life.",
    ],
    signoff: "Have a brilliant and prosperous year ahead!",
  },

  finale: {
    eyebrow: "Final level · timed birthday itinerary",
    heading: "Five surprises for Ritika",
    intro: "Reveal the wand now. Its magic seals the next ticket for eight hours and thirty minutes; after that, each new surprise unlocks one hour after the last.",
  },

  finaleTickets: [
    {
      id: "wand",
      label: "Surprise no. 01",
      title: "The Wand Chooses Ritika",
      location: "A physical gift, chosen for you",
      validFrom: "OPEN ON YOUR BIRTHDAY",
      clue: "Every witch deserves a wand of her own.",
      redemption: "Say your favourite spell and open the first gift.",
      code: "WITCH-AGED-26",
      icon: "✧",
      image: publicAsset("/surprises/harry-potter-wand.webp?v=1"),
      imageAlt: "An elegant magical wand presented in a velvet gift box",
    },
    {
      id: "the-shard",
      label: "Surprise no. 02",
      title: "A Date Above London",
      location: "The Shard, London",
      validFrom: "DATE TO BE REVEALED",
      clue: "Dress up for an unforgettable view from one of London's tallest buildings.",
      redemption: "Bring yourself, your camera, and absolutely no fear of heights.",
      code: "SKY-HIGH-26",
      icon: "✦",
      image: publicAsset("/surprises/the-shard.webp?v=1"),
      imageAlt: "A cinematic evening view from The Shard over London",
    },
    {
      id: "south-indian-lunch",
      label: "Surprise no. 03",
      title: "A South Indian Feast",
      location: "Saravana Bhavan or another favourite",
      validFrom: "WHEN HUNGER STRIKES",
      clue: "A table full of comforting South Indian favourites—with plenty of rice, naturally.",
      redemption: "Arrive hungry. Choosing only one dish is not required.",
      code: "SAAPADU-READY",
      icon: "🍚",
      image: publicAsset("/surprises/south-indian-lunch.webp?v=1"),
      imageAlt: "An elegant South Indian vegetarian meal served on a banana leaf",
    },
    {
      id: "thames-cruise",
      label: "Surprise no. 04",
      title: "A Cruise Through London",
      location: "The River Thames",
      validFrom: "SAILING SOON",
      clue: "London landmarks, river views, and a boat ride through the heart of the city.",
      redemption: "Meet at the pier and let London provide the scenery.",
      code: "RITIKA-SETS-SAIL",
      icon: "⚓",
      image: publicAsset("/surprises/thames-cruise.webp?v=1"),
      imageAlt: "A romantic evening boat cruising along the Thames in London",
    },
    {
      id: "harry-potter-studio",
      label: "Surprise no. 05",
      title: "The Making of Harry Potter",
      location: "Warner Bros. Studio Tour London",
      validFrom: "MISCHIEF MANAGED SOON",
      clue: "Real sets, magical creatures, costumes, and a world you have always loved.",
      redemption: "Wait for your owl—and prepare for a properly magical day.",
      code: "PLATFORM-9¾",
      icon: "⚡",
      image: publicAsset("/surprises/harry-potter-studio.webp?v=1"),
      imageAlt: "A cinematic magical film studio interior with floating candles",
    },
  ],
};
